### PR TITLE
react native 0.71 support

### PR DESCRIPTION
**Pull request by krudos**
fix building error when using react native 0.71

### CODE REVIEW

**Comment by oblador** [comment]
Thanks for your PR! When I was trying it out with example project on RN 0.71 it crashed on start. Would you mind rebasing on top of this PR and ensuring that it works with new arch enabled (turned off in the PR): https://github.com/klarna-incubator/react-native-vector-drawable/pull/11

By the way, I'd suggest we drop support for fabric in <0.69 as the auto linking makes it so much cleaner and I'd argue whoever is using fabric in 0.69 will likely already have upgraded to 0.70+.

**Comment by krudos** [comment]
> Thanks for your PR! When I was trying it out with example project on RN 0.71 it crashed on start. Would you mind rebasing on top of this PR and ensuring that it works with new arch enabled (turned off in the PR): #11
> 
> By the way, I'd suggest we drop support for fabric in <0.69 as the auto linking makes it so much cleaner and I'd argue whoever is using fabric in 0.69 will likely already have upgraded to 0.70+.

ok, let me rebase

**Comment by oblador** [comment]
Does it work for you? Make sure to enable new arch in `gradle.properties` first.

**Comment by krudos** [comment]
> Does it work for you? Make sure to enable new arch in `gradle.properties` first.

nop, is crashing because it can't find libvectordrawable_modules.so
i am checking, it appears is not include in the apk build

**Comment by krudos** [comment]
> Does it work for you? Make sure to enable new arch in `gradle.properties` first.

i think this will need a bigger refactor using the instructions on https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components#android

i will try to check this week and send a new PR

**Pull request closed without merging**
